# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "fukurou_helpers"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
lazy_static = "1.4.0"
rayon = "1.7"
