# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "fukurou_player"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
fukurou_core = { workspace = true }
